=== suyogsakegaonkar/digitalriver-assignment/target/classes/xsd/DataSet.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/DataSet"
	xmlns:tns="http://www.example.org/DataSet" elementFormDefault="qualified">

	<element name="pageData">
		<complexType>
			<sequence>
				<element name="countryDetails" type="tns:countryDetails"
					maxOccurs="unbounded" minOccurs="0" />
				<element name="googleSearch" type="tns:googleSearch"
					maxOccurs="unbounded" minOccurs="0" />


			</sequence>
		</complexType>
	</element>

	<complexType name="countryDetails">
		<sequence>
			<element name="countryName" type="string" />
			<element name="isoCode" type="string" />
			<element name="callingCode" type="string" />
		</sequence>
		<attribute name="id" type="ID"></attribute>
	</complexType>

	<complexType name="googleSearch">
		<sequence>
			<element name="searchText" type="string" />
			<element name="linkDescText" type="string" />
			<element name="linkText" type="string" />
		</sequence>
		<attribute name="id" type="ID"></attribute>
	</complexType>

</schema>

=== suyogsakegaonkar/digitalriver-assignment/src/main/resources/xml/Data.xml
<?xml version="1.0"?>

<pageData xmlns="http://www.example.org/DataSet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/DataSet ../src/test/resources/xsd/DataSet.xsd ">

	<countryDetails id="germany">
		<countryName>Germany</countryName>
		<isoCode>DE</isoCode>
		<callingCode>49</callingCode>
	</countryDetails>

	<countryDetails id="japan">
		<countryName>Japan</countryName>
		<isoCode>JP</isoCode>
		<callingCode>81</callingCode>
	</countryDetails>

	<googleSearch id="germany">
		<searchText>phone number of the german digital river office
		</searchText>
		<linkDescText>phone,number,germany,office</linkDescText>
		<linkText>digital,river</linkText>
	</googleSearch>

	<googleSearch id="japan">
		<searchText>phone number of the japan digital river office
		</searchText>
		<linkDescText>phone,number,japan,office</linkDescText>
		<linkText>digital,river</linkText>
	</googleSearch>

</pageData>

=== suyogsakegaonkar/digitalriver-assignment/target/classes/xml/Data.xml
<?xml version="1.0"?>

<pageData xmlns="http://www.example.org/DataSet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/DataSet ../src/test/resources/xsd/DataSet.xsd ">

	<countryDetails id="germany">
		<countryName>Germany</countryName>
		<isoCode>DE</isoCode>
		<callingCode>49</callingCode>
	</countryDetails>

	<googleSearch id="germany">
		<searchText>phone number of the german digital river office</searchText>
		<linkDescText>phone,number,germany,office</linkDescText>
		<linkText>digital,river</linkText>
	</googleSearch>

</pageData>
